name: Build FFmpeg

on:
  workflow_dispatch:
    inputs:
      architecture:
        description: "Select architecture to build"
        required: true
        default: "both"
        type: choice
        options:
          - win32
          - win64
          - both
      version:
        description: "FFmpeg version to checkout"
        required: false
        default: "n6.0"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Determine architecture
        id: determine-arch
        run: |
          if [[ "${{ inputs.architecture }}" == "both" ]]; then
            echo "arch=multi" >> $GITHUB_ENV
          else
            echo "arch=${{ inputs.architecture }}" >> $GITHUB_ENV
          fi

      - name: Checkout ffmpeg-windows-build-helpers
        uses: actions/checkout@v4
        with:
          repository: rdp/ffmpeg-windows-build-helpers
          ref: master
          persist-credentials: false

      - name: Install APT dependencies
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: subversion ragel curl texinfo g++ ed bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev unzip pax nasm gperf autogen bzip2 autoconf-archive p7zip-full meson clang python3-distutils python-is-python3 mingw-w64 mingw-w64-tools mingw-w64-x86-64-dev libtool-bin

      - name: Install pip dependencies
        run: sudo -H pip3 -qq install meson ninja

      - name: Pre-conf
        run: sudo autoreconf -fi

      - name: Compile FFmpeg for ${{ env.arch }}
        run: |
          ./cross_compile_ffmpeg.sh \
            --ffmpeg-git-checkout-version=${{ inputs.version }} \
            --compiler-flavors=${{ env.arch }} \
            --gcc-cpu-count=$(nproc) \
            --sandbox-ok=y

      - name: Find generated archive
        id: find-archive
        run: |
          archive_path=$(find $GITHUB_WORKSPACE/ffmpeg-windows-build-helpers/sandbox/redist/ -name "*.7z" | head -n 1)
          echo "archive_path=$archive_path" >> $GITHUB_ENV

      - name: Upload FFmpeg archive
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-${{ env.arch }}
          path: ${{ env.archive_path }}
